hover states
inovex/scrumlr.io pull request #1901
Opened 2022-06-28 09:04 UTC by Resaki1

## Description

Added missing hover states to (hopefully) all interactive elements.

## Changelog

- added hover states for interactive elements that didn't have hover states before
- using the standard toggle component in the settings dialog now for consistent design

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The light- and dark-theme are both supported and tested
- [x] The design was implemented and is responsive for all devices and screen sizes
- [x] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

2022-07-11 10:08 UTC, CronJorian requested changes
Just some minor requests.

2022-07-11 10:08 UTC, CronJorian commented on src/components/VotingDialog/VotingDialog.scss
> +    box-shadow: 0 6px 9px 0 rgba(var(--accent-color-rgb), 0.24);
At least make it consistent to the other shadows and use 4 8 or 8 16. Or is there a reason to use these specific values?

2022-07-12 09:02 UTC, Resaki1 commented on src/components/SettingsDialog/Components/AvatarSettings.scss
> +      }
yes. Transform is applied to both and the existing background and shadow for darkmode are fine imo

2022-07-12 09:49 UTC, CronJorian approved these changes

2022-07-12 09:50 UTC, merged