Small UI fixes
inovex/scrumlr.io pull request #2209
Opened 2022-09-30 14:10 UTC by Resaki1

## Description

Fixed a few small UI bugs.

## Changelog

- delete icon is now accent color in stack view again
- nodes of stack view are now properly cut at the bottom of the screen
- the text color of the me chip in the stack view is now black, to match the color of the me chips on the board
- the delete column icon is now centered

## Visual Changes

### Before

<img width="1680" alt="Bildschirmfoto 2022-09-30 um 16 03 24" src="https://user-images.githubusercontent.com/35272402/193288091-0ef86034-03bc-4368-926c-995f9285119a.png">
<img width="230" alt="Bildschirmfoto 2022-09-30 um 16 03 34" src="https://user-images.githubusercontent.com/35272402/193288089-745ad7f6-9b7d-46c3-8be4-0579a2687d22.png">

### After
<img width="1680" alt="Bildschirmfoto 2022-09-30 um 16 03 53" src="https://user-images.githubusercontent.com/35272402/193288085-79445019-24bf-43c6-b649-f05f293c4db7.png">
<img width="222" alt="Bildschirmfoto 2022-09-30 um 16 04 00" src="https://user-images.githubusercontent.com/35272402/193288083-8bc5473a-6a8d-490b-b81a-d7013b00d140.png">

2022-10-05 07:11 UTC, CronJorian requested changes

2022-10-05 07:11 UTC, CronJorian commented on src/routes/StackView/StackView.scss
> +$stack-view__parent-note-height: 22%;
Personally not a fan but this will suffice.

2022-10-05 07:11 UTC, CronJorian commented on src/components/NoteDialogComponents/NoteDialogNoteWrapper.scss
>    overflow-x: hidden;
imo a bottom padding/margin would be great so that the last note does not stick at the bottom but has a bit space to breathe

2022-10-07 08:44 UTC, Resaki1 commented on src/assets/icon-delete.svg
>          <path d="M1,6.75A.75.75,0,0,1,.25,6V0a.75.75,0,0,1,1.5,0V6A.75.75,0,0,1,1,6.75Z" transform="translate(9 -13.5)" opacity="0.5"/>
That's what it was like before and why it didn't work. But setting the color of the tooltip-button__icon to the accent color with a fallback helped, thanks 🙏

2022-10-07 09:23 UTC, CronJorian commented on src/assets/icon-delete.svg
>          <path d="M1,6.75A.75.75,0,0,1,.25,6V0a.75.75,0,0,1,1.5,0V6A.75.75,0,0,1,1,6.75Z" transform="translate(9 -13.5)" opacity="0.5"/>
No before the g tag hat the fill attribute, not every path tag. If you use it in every path tag it will work as supposed (tested it ❤️‍🔥 )

2022-10-07 09:31 UTC, CronJorian approved these changes
![image](https://user-images.githubusercontent.com/44020029/194522246-22b60ac4-9540-4d05-9820-03eb790bab2f.png)

2022-10-07 09:37 UTC, merged