Add board-layout
inovex/scrumlr.io pull request #224
Opened 2020-11-16 18:17 UTC by alphapfote

2020-11-17 09:14 UTC, brandstetterm requested changes

2020-11-17 09:14 UTC, brandstetterm commented on src/components/Board/Board.tsx
> +        if (intersectionObserverRef.current !== null) {
Was genau ist ein intersectionObserver und wieso muss der deaktiviert werden?

2020-11-18 08:47 UTC, alphapfote commented on src/components/Board/Board.tsx
> +import {ReactComponent as LeftArrowIcon} from "../../assets/icon-arrow-previous.svg";
Alles klar, danke für den Tipp. Ich habe die Imports entsprechend umbenannt.

2020-11-18 08:49 UTC, alphapfote commented on src/assets/icon-add.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg>
Ja, sind schon minified

2020-11-18 09:11 UTC, alphapfote commented on src/components/Board/Board.tsx
> +        if (intersectionObserverRef.current !== null) {
Der intersectionObserver ist dazu da, um zu schauen, welche Columns aktuell angezeigt werden, z.B. um auch die Farbe den Columns zuordnen zu können etc... 
Jedes Mal, wenn sie die Children (also die Columns) verändern, wird useEffect neu aufgerufen, also z.B. wenn eine Spalte umbenannt oder hinzugefügt/entfernt wird. Da wir nicht irgendwann unendlich viele intersectionObserver haben möchten, wird (falls vorhanden) der alte Observer disconnected (Zeile 27-29) und ein neuer intersectionObserver erstellt (Zeile 53).

2020-11-20 08:49 UTC, brandstetterm commented on src/components/Board/Board.tsx
> +        if (intersectionObserverRef.current !== null) {
Okay 👍

2020-11-20 09:24 UTC, brandstetterm commented on src/components/Column/Column.scss
> +  // box-shadow: 0 6px 9px 0 rgba(0,87,255,0.16);
Brauchst du die ganzen Kommentare noch?

2020-11-20 09:24 UTC, brandstetterm commented on src/components/Board/Board.test.tsx
> +        // Infinite loop was removed to enhance usability
Brauchst du die Kommentare hier noch?

2020-11-20 09:52 UTC, brandstetterm approved these changes

2020-11-20 13:22 UTC, brandstetterm commented on src/components/Column/Column.tsx
> +                    <h1 className="column__header-card-number">5</h1>
Zweimal h1

2020-11-20 13:22 UTC, brandstetterm commented on src/components/Column/Column.scss
> +  // font-family: Raleway;
Hier sind noch Kommentare vom Font

2020-12-04 12:28 UTC, alphapfote commented
![image](https://user-images.githubusercontent.com/28045496/101163873-9327f200-3634-11eb-8aa3-3617ebd71009.png)

2020-12-04 12:29 UTC, alphapfote commented
**Mobile Ansicht:** 
![image](https://user-images.githubusercontent.com/28045496/101163985-c074a000-3634-11eb-934f-12e49a665d99.png)

2020-12-04 13:16 UTC, brandstetterm requested changes

2020-12-10 15:37 UTC, alphapfote commented on src/components/Column/Column.tsx
> +                    <p className="column__add-card__text">Add your note...</p>
Gute Frage. Wir benutzen ja BEM fürs Naming, d.h. eigentlich hat das ganze den Aufbau block__element--modifier
Ich habe es jetzt mal 'add-card__text' genannt und das 'column__add-card' dann aber auch in 'add-card' umbenannt, sodass add-card hier der block ist

2020-12-10 15:39 UTC, alphapfote commented on src/components/Column/Column.tsx
> +                    <p className="column__add-card__text">Add your note...</p>
Oder man sagt eben 'column__add-card', 'column__add-card-text' und 'column__add-card-icon', dann wäre es genauso wie beim Header obendrüber.

2020-12-10 15:42 UTC, bitionaire commented on src/components/Column/Column.tsx
> +                    <p className="column__add-card__text">Add your note...</p>
... oder man macht eine weitere Komponente die `NoteInput` heisst. Dann heissen die Klassen auch `note-input__...` und Card ist dann auch schonmal in Note umbenannt :)

2020-12-10 15:46 UTC, alphapfote commented on src/components/Column/Column.tsx
> +                    <p className="column__add-card__text">Add your note...</p>
Gute Idee. Früher oder später ist es sowieso sinnvoll, das ganze in eine eigene Komponente zu packen.

2020-12-10 16:14 UTC, alphapfote commented on src/components/Column/Column.scss
> +  height: 100%;
Done

2020-12-10 16:14 UTC, alphapfote commented on src/components/Column/Column.scss
> +  width: auto;
Done

2020-12-10 16:15 UTC, alphapfote commented on src/components/Column/Column.scss
> +  display: flex;
Wird benötigt, da die Zahl sonst nicht neben der Überschrift steht

2020-12-10 16:56 UTC, alphapfote commented on src/components/Column/Column.tsx
> +                    <p className="column__add-card__text">Add your note...</p>
Done

2020-12-14 11:17 UTC, brandstetterm approved these changes

2020-12-14 11:29 UTC, merged