improvement: Improve SettingsDialog
inovex/scrumlr.io pull request #2545
Opened 2022-12-29 12:48 UTC by brandstetterm

## Changelog

- Change black background to colored background (backlog-blue in light-mode & planning-pink in dark-mode)
- Add transition to SettingsDialog
- Use style constants introduced in `mb/leave-board-dialog` branch

## Visual Changes

### Before
<img width="1483" alt="Screenshot 2022-12-29 at 13 45 15" src="https://user-images.githubusercontent.com/36969812/209953225-34f5ffd3-0dfa-452c-8967-7420335d466b.png">
<img width="1485" alt="Screenshot 2022-12-29 at 13 45 30" src="https://user-images.githubusercontent.com/36969812/209953235-b7568edd-e8e1-4676-9860-25b16f4e0fe3.png">

### After

<img width="1489" alt="Screenshot 2022-12-29 at 13 44 53" src="https://user-images.githubusercontent.com/36969812/209953251-f387bd97-002c-4173-8e7f-06e7ab46e9a7.png">

<img width="1485" alt="Screenshot 2022-12-29 at 13 45 48" src="https://user-images.githubusercontent.com/36969812/209953255-cb3f6122-7e68-4a48-84c2-c36417c9558a.png">

2023-01-07 15:49 UTC, Resaki1 requested changes
personally, I'd speed up the animation a little so the dialog can be interacted with sooner, but that's just my preference.
Also, on mobile the slide in looks kinda weird imo

2023-01-07 15:49 UTC, Resaki1 commented on src/constants/style.scss
> +$rounded--full: 9999px;
```suggestion
$rounded--full: 100%;
```

2023-01-07 15:55 UTC, Resaki1 approved these changes

2023-01-07 16:06 UTC, Resaki1 requested changes

2023-01-07 16:06 UTC, Resaki1 commented on src/components/SettingsDialog/SettingsDialog.tsx
> +import React, {useEffect} from "react";
```suggestion
import {useEffect, FC} from "react";
```

2023-01-07 16:06 UTC, Resaki1 commented on src/components/SettingsDialog/SettingsDialog.tsx
> +export const SettingsDialog: React.FC = () => {
```suggestion
export const SettingsDialog: FC = () => {
```

2023-01-09 12:56 UTC, brandstetterm commented
> personally, I'd speed up the animation a little so the dialog can be interacted with sooner, but that's just my preference. Also, on mobile the slide in looks kinda weird imo

Personally, I don't think the transition duration is too long. 
I've added an additional transition config which will be used for screens smaller than 450px (when the dialog is fullscreen).

2023-01-11 13:15 UTC, merged