Bf/stack deletion dialogs
inovex/scrumlr.io pull request #2721
Opened 2023-03-02 12:58 UTC by Benjosh95

## Description
Deletion of parent note doesn't remove children notes anymore unless its intentional.
Different actions get handled now by confirmation dialogs. 

## Changelog
Changed stack references of children of old parent to next parent before deletion.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] The light- and dark-theme are both supported and tested
- [ ] The design was implemented and is responsive for all devices and screen sizes
- [ ] The application was tested in the most commonly used browsers (e.g. Chrome, Firefox, Safari)

## (Optional) Visual Changes

[//]: <> (If available, please provide a before and after screenshot of your UI related changes.)

https://user-images.githubusercontent.com/49522775/195931286-f559d3fb-8877-4a97-99ca-6daee1d745a7.mp4

2023-03-24 11:21 UTC, Resaki1 requested changes

2023-03-24 11:21 UTC, Resaki1 commented on src/components/ConfirmationDialog/ConfirmationDialog.scss
> +  letter-spacing: 0.25px;
```suggestion
  letter-spacing: $letter-spacing--small;
```

2023-03-24 11:21 UTC, Resaki1 commented on src/components/ConfirmationDialog/ConfirmationDialog.scss
> +@media screen and (max-width: 450px) {
```suggestion
@media #{$mini-smartphone} {
```

2023-03-24 11:21 UTC, Resaki1 commented on src/components/ConfirmationDialog/ConfirmationDialog.scss
> +  box-shadow: 0 16px 32px 0 rgb(0 87 255 / 24%);
```suggestion
  box-shadow: 0 16px 32px 0 rgba($color-backlog-blue, 0.24);
```

2023-03-24 11:21 UTC, Resaki1 commented on src/components/ConfirmationDialog/ConfirmationDialog.scss
> +    box-shadow: 0 16px 32px 0 rgba(0, 0, 0, 0.2);
```suggestion
    box-shadow: $box-shadow--dark;
```

2023-03-24 11:21 UTC, Resaki1 commented on src/components/ConfirmationDialog/ConfirmationDialog.scss
> +    box-shadow: 0 16px 32px 0 rgba(0, 0, 0, 0.2);
```suggestion
    box-shadow: $box-shadow--dark;
```

2023-03-24 11:42 UTC, Resaki1 commented
@brandstetterm @BenedictHomuth could one of you review the backend code?

2023-03-28 20:03 UTC, Benjosh95 commented
@Resaki1 Thank you for the review :)! Fixed the points as u suggested.

2023-04-18 14:10 UTC, Resaki1 approved these changes

2023-04-25 11:16 UTC, Benjosh95 commented on server/src/database/notes.go
> +			Where("id = ? AND shared_note = ?", board, id)
No, there is no specific reason. I guess i liked it more in that order :D

2023-04-27 17:03 UTC, Benjosh95 commented on server/src/database/notes_test.go
> +func testDeleteStackParent(t *testing.T) {
Thank you. I improved the test in this commit "fix updateRanks bug, improve tests"

2023-04-27 19:06 UTC, merged