improvements: add toast notification for toggle hotkeys
inovex/scrumlr.io pull request #2822
Opened 2023-03-31 09:53 UTC by brandstetterm

2023-04-18 15:28 UTC, Resaki1 requested changes
Idk if this is a new bug or not, but when multiple hotkeys are activated after another, the toasts are added to a queue. Which is fine, however every toast that is in the queue now appears two times:

https://user-images.githubusercontent.com/35272402/232825958-951c98b1-9ba5-4bd7-ba2b-f354aaca606e.mov

2023-04-18 15:28 UTC, Resaki1 commented on public/locales/de/translation.json
> +      "hide": "Ausgeblendete Spalten sind nun für dich ausgeblendet",
```suggestion
      "hide": "Ausgeblendete Spalten sind nun auch für dich ausgeblendet",
```

2023-04-18 15:28 UTC, Resaki1 commented on public/locales/de/translation.json
> +      "hide": "Die Kärtchen anderer Teilnehmer sind ausgeblendet",
```suggestion
      "hide": "Die Kärtchen anderer Teilnehmer sind nun ausgeblendet",
```

2023-04-18 15:28 UTC, Resaki1 commented on public/locales/de/translation.json
> +      "hide": "Die Autoren der Kärtchenn sind ausgeblendet",
```suggestion
      "hide": "Die Autoren der Kärtchen sind  nun ausgeblendet",
```

2023-04-18 15:28 UTC, Resaki1 commented on public/locales/en/translation.json
> +      "hide": "The notes of other participants are hidden",
```suggestion
      "hide": "The notes of other participants are now hidden",
```

2023-04-18 15:28 UTC, Resaki1 commented on public/locales/en/translation.json
> +      "hide": "The authors of the notes are hidden",
```suggestion
      "hide": "The authors of the notes are now hidden",
```

2023-04-19 07:08 UTC, brandstetterm commented
> Idk if this is a new bug or not, but when multiple hotkeys are activated after another, the toasts are added to a queue. Which is fine, however every toast that is in the queue now appears two times:
> 
>  Bildschirmaufnahme.2023-04-18.um.17.28.43.mov

Thanks for the review. That's very strange behaviour and I'll try to fix it 👍🏼

2023-04-19 15:14 UTC, Resaki1 approved these changes

2023-04-19 15:23 UTC, merged