Delete and edit note
inovex/scrumlr.io pull request #331
Opened 2021-04-09 11:50 UTC by alphapfote

2021-06-01 08:52 UTC, brandstetterm requested changes

2021-06-01 08:52 UTC, brandstetterm commented on src/components/IconButton/IconButton.scss
> +  // TODO: color: var(--accent-color);
Ah I guess you need to replace `color: violet` with `color: var(--accent-color)` so that the button uses the column color

2021-06-01 08:52 UTC, brandstetterm commented on src/components/IconButton/IconButton.tsx
> +function IconButton(props: IconButtonProps) {
Is it maybe possible to reuse MenuButton for this one (or replace MenuButton with IconButton) so we don't have duplicate code?

2021-06-01 08:52 UTC, brandstetterm commented on src/components/Note/Note.tsx
> +  noteId?: string;
Can this be undefined?

2021-06-01 08:52 UTC, brandstetterm commented on src/components/NoteDialog/NoteDialog.scss
> +  width: fit-content;
Invalid property value

2021-06-01 08:52 UTC, brandstetterm commented on src/components/NoteDialog/NoteDialog.scss
> +  font: inherit;
You can delete `font-size: 100%` because `font: inherit` also sets font-size to inherit

2021-06-01 08:52 UTC, brandstetterm commented on src/components/IconButton/IconButton.scss
> +.icon-button {
Maybe you could also set `cursor: pointer` to visualize that it's clickable

2021-06-01 08:52 UTC, brandstetterm commented on src/components/Note/Note.tsx
> +import "./Note.scss";
Maybe you could also set `cursor: pointer` for `.note` to visualize that it's clickable

2021-06-01 08:52 UTC, brandstetterm commented on src/components/NoteDialog/NoteDialog.tsx
> +  onClose?: () => void;
Why can `onClose()` be undefined?

2021-08-03 13:05 UTC, bitionaire approved these changes

2021-08-03 13:34 UTC, brandstetterm approved these changes

2021-08-03 13:34 UTC, merged